### ISSUE TITLE
Initialize end_path_s and end_path_d with first s and d from simulator

### ISSUE THREAD

**Issue by jhallier** [TeenageMutantNinjaTurtlesAllTheWayDown/CarND-Capstone#2]
end_path_s and end_path_d are the s and d values of the last planned path. After init of the simulator, no previous path is available and both variables are set to zero. However, the first position of the simulator is not at s,d = 0,0, but rather at somewhere around 124, 6. 

The issue with this is if you use the last planned s and d to plan your next trajectory, in the first round, you need to manually catch this and set both variables to the current s and d from the simulator. Only after the first path is planned, both variables are correctly initialized. I suggest to initialize them both with the starting position of s and d in the simulator at t=0, because this also reflects the situation that your current s and d, without any planned path, are basically the end of your planned path with path length = 0.

**Comment by HenryDev** [comment]
@jhallier what's your question?

**Comment by jhallier** [comment]
I don't know why this ended up on your page, I thought I posted on the udacity term3 simulator page. Sorry about that, I'll close it here.
